name: nurulquran
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.3
  google_sign_in: ^5.2.1
  provider: ^6.0.1
  shared_preferences: ^2.0.11
  fluttertoast: ^8.0.8
  intl_phone_field: ^2.1.0
  video_player: ^2.2.18
  image_picker: ^0.8.4+4
  extended_image: ^6.0.1
  camera: ^0.9.4+5
  rename: ^2.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  uuid: ^3.0.5
  intl: ^0.17.0
  dio: ^4.0.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  android: true
  ios: true
  image: "assets/images/logo.png"
  color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
